language: node_js

sudo: false

node_js:
    - 8

env:
    global:
        - secure: VSpgvnHMYfOnJNjCMZqGE9tmautFPmsGhueBpZkn66TU45EIfy8ZfAnkjZLcjbNAxYftM0i/s1a+DQN4/IbS/DK1h7IhE5QYMvYTgL81dqUm6I3TghVTx0WxHJBSePeCdv+Zwv2SMNOXNX/KnHTOnIKk/catCFw5Q30Lij01rUI=
        - secure: a8KaTHbJvZdxTY/eORok3v8ljQwcbzfRmSEF9Ot4GI0g8KLza/I8q+KOCkfQKQ901H5ddQ5IqaRy9rZa+DyjR4BUXinYRB6qg88moQwDZWQaJ+jNyEaBPxgZBBaPlY1xEryEFLzIJ9zPWHBaii0Vn9VXNq42Jv/KOwMfa39MHl4=

cache:
    directories:
        - node_modules

install:
    - yarn
    - yarn build-css

before_script:
    - greenkeeper-lockfile-update

script:
    - yarn cs -l
    - yarn test
    - PUBLIC_URL=/semver-check yarn build

after_script:
    - greenkeeper-lockfile-upload

deploy:
    provider: pages
    skip_cleanup: true
    github_token: '$GITHUB_TOKEN'
    local_dir: build
    on:
        branch: master
